# Generated by Django 4.2.5 on 2023-12-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Book'), (2, 'Detail')])),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('author', models.CharField(max_length=255)),
                ('rate', models.IntegerField()),
                ('page', models.IntegerField()),
                ('year', models.DateField()),
                ('about', models.TextField()),
                ('time', models.IntegerField()),
                ('mb', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('rate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('author', models.CharField(max_length=255)),
                ('rate', models.IntegerField()),
                ('page', models.IntegerField()),
                ('year', models.DateField()),
                ('about', models.TextField()),
                ('time', models.IntegerField()),
                ('mb', models.IntegerField()),
            ],
        ),
    ]
