# Generated by Django 4.2.5 on 2023-12-09 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_detail_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BD',
            new_name='BDe',
        ),
    ]
