# Generated by Django 4.2.5 on 2023-12-09 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_bd_bde'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
